### PR TITLE
Remove unnecessary rlimit adjustments on macOS

### PR DESCRIPTION
**Pull request by dominiklohmann**

### CODE REVIEW

**Review by mavam — APPROVED** [review]
Looks good content-wise.

It would be nice to get an understanding why this is not longer necessary. What's the current number of default descriptors?

**Comment by dominiklohmann** [comment]
> It would be nice to get an understanding why this is not longer necessary. What's the current number of default descriptors?

Whatever `launchctl limit` returns on macOS for `maxfiles`. On my system, that's 256 soft limit, unlimited hard limit. I'm not quite sure why this was necessary in the first place. It's the job of the launchd configuration file (e.g., `~/Library/LaunchAgents/com.tenzir.vast.plist`) to set the resource limits.

**Comment by mavam** [comment]
256 sounds awefully low and was probably the reason why I introduced this adjustment in the first place. Before merging, I'd like to get a bit more extensive tests that this doesn't re-introduce a regression.

**Comment by dominiklohmann** [comment]
Merging after quick discussion via Slack.

**Pull request merged**
