### PR TITLE
Measure time spent in archive and index separately in exporter

### PR DESCRIPTION
**Pull request by dominiklohmann**
###  :notebook_with_decorative_cover: Description

This PR measures the time spent waiting per request to index and archive and prints the results to DEBUG after the exporter shuts down.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

File-by-file.

### CODE REVIEW

**Review by tobim — CHANGES_REQUESTED** [review]
To me, the size of this change is a strong indicator that the communication protocol between `index` and `exporter` is neither scalable nor maintainable. Almost all of the effort is spent to implement request tracking through the index to collect some data that is very hard to interpret correctly.

The original need to add more query instrumentation came from the desire to get an answer to "Which component was responsible for the majority of the runtime duration of a call to `vast export`?"
The only measurements that we actually need for that is the (mean, max and overall) amount of time that passes between subsequent requests to the index. The time spent in the archive doesn't even need to be considered, because the absolute query time is already available.

I apologize for not making this clear at the start.

**Comment by dominiklohmann** [comment]
Your change request does not contain a request for changes @tobim. Please clarify.

**Comment by tobim** [comment]
To clarify: This PR is blocked until the disagreement about the general approach is resolved.

**Comment by dominiklohmann** [comment]
Closing as we plan to pursue this in a different way in the future.

**Pull request closed without merging**
