### PR TITLE
Add back human-readable build summary

### PR DESCRIPTION
**Pull request by dominiklohmann**
###  :notebook_with_decorative_cover: Description

This adds a minimal version of the old build summary per request by @mavam, whom I've requested for review explicitly.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Checkout the branch and test locally.

### CODE REVIEW

**Comment by mavam** [comment]
This is a good start. The most important information for troubleshooting is still missing though: the location of the dependencies that CMake picked up.

**Comment by dominiklohmann** [comment]
> This is a good start. The most important information for troubleshooting is still missing though: the location of the dependencies that CMake picked up.

Done. Please check back.

**Review by mavam — COMMENTED** [review]
This looks pretty good now. I get this output when I try it out:

```
-- Using AppleClang 11.0.3.11030032
-- Found libpcap: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libpcap.tbd
-- Found CAF


-- The following features have been enabled:

 * BUILD_SHARED_LIBS, build shared instead of static libraries.

 * VAST_ENABLE_RELOCATABLE_INSTALLATIONS, enable relocatable installations.
 * VAST_ENABLE_SDT, generate USDT tracepoint instrumentation.
 * VAST_ENABLE_ASSERTIONS, enable assertions.
 * VAST_ENABLE_DEVELOPER_MODE, enables build settings for a nicer development environment.
 * VAST_ENABLE_BUNDLED_SCHEMAS, install bundled schemas with VAST.
 * VAST_ENABLE_ARROW, build with Apache Arrow support.
 * VAST_ENABLE_PCAP, build with PCAP support.
 * VAST_ENABLE_OPENSSL, encrypt network communication.
 * VAST_ENABLE_UNIT_TESTS, build unit tests for libvast.
 * VAST_ENABLE_VAST, build the standalone vast binary.

-- The following features have been disabled:

 * VAST_ENABLE_BUILDID, a unique identifier in the ELF notes section.
 * VAST_ENABLE_TIME_REPORT, print information where time was spent during compilation.
 * VAST_ENABLE_ASAN, inserts pointer and reference checks into the generated binaries.
 * VAST_ENABLE_UBSAN, adds run-time checks for undefined behavior into the generated binaries.
 * VAST_ENABLE_STATIC_EXECUTABLE, link VAST statically.
 * VAST_ENABLE_JEMALLOC, use jemalloc instead of libc malloc.
 * VAST_ENABLE_MORE_WARNINGS, enable additional warnings.
 * VAST_ENABLE_BUNDLED_CAF, always use the CAF submodule.
 * VAST_ENABLE_DSCAT, build the dscat utility.
 * VAST_ENABLE_LSVAST, build the lsvast debugging utility.
 * VAST_ENABLE_ZEEK_TO_VAST, build the zeek-to-vast relay utility (requires Broker 1.3.1).
 * VAST_ENABLE_CORELIGHT_CAT, install corelight-cat with VAST.

-- Build summary:

 * Version: 2020.12.16-58-g76e5c8bf3

 * Build Type: RelWithDebInfo
 * Source Directory: /Users/mavam/code/tenzir/vast
 * Binary Directory: /Users/mavam/code/tenzir/vast/build/review

 * C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc (AppleClang)
 * C Compiler Flags:
 * C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++ (AppleClang)
 * C++ Compiler Flags:
 * Linker: /Library/Developer/CommandLineTools/usr/bin/ld
 * Archiver: /Library/Developer/CommandLineTools/usr/bin/ar

 * CAF: /usr/local/lib/libcaf_core.dylib
 * FlatBuffers: /usr/local/include
 * yaml-cpp: /usr/local/include
 * Apache Arrow: /usr/local/include
 * PCAP: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mavam/code/tenzir/vast/build/review
```

Why are the CC/CXX flags empty?

Also, a nit, but there seems to be a lot of whitespace at the beginning:

```
-- Using AppleClang 11.0.3.11030032
-- Found libpcap: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libpcap.tbd
-- Found CAF


-- The following features have been enabled:
```

**Comment by dominiklohmann** [comment]
> Why are the CC/CXX flags empty?

That's because they're only the _additional_ `{C,CXX}_FLAGS` set by the user, not the ones we set for VAST's internal target. Since the CMake refactoring we don't set our own flags globally anymore.

> Also, a nit, but there seems to be a lot of whitespace at the beginning:

That we cannot fix, unless we silence CAF completely. We'll have to live with it until CAF 0.18 comes out.

**Comment by mavam** [comment]
> That's because they're only the additional {C,CXX}_FLAGS set by the user, not the ones we set for VAST's internal target. Since the CMake refactoring we don't set our own flags globally anymore.

Got it. It's only misleading to call it that way. You could prefix it with "extra" or "additional" to make it clear that these are not the builtin ones. I highly doubt that users typically tweak their flags, so to me the field has little value in its current form. Maybe we can show them only if they are not empty?

 > That we cannot fix, unless we silence CAF completely. We'll have to live with it until CAF 0.18 comes out.

Works for me.

**Comment by dominiklohmann** [comment]
@mavam looks like this now for me:

```
 * C Compiler: /usr/local/opt/ccache/libexec/clang (Clang 11.0.0)
 * CXX Compiler: /usr/local/opt/ccache/libexec/clang++ (Clang 11.0.0 with -isystem /usr/local/opt/llvm/include/c++/v1)
```

**Review by mavam — APPROVED** [review]
I tested it locally as well, work for me for now!

**Pull request merged**
