### PR TITLE
Rename `vast dump` to `vast show`

### PR DESCRIPTION
**Pull request by dominiklohmann**
We're planning to do more with the mostly internal command in the near future, and to quote @lava on the matter:

> I wanna take the opportunity to suggest renaming `vast dump` to `vast
> show`, since `dump` sounds like some kind of backup or debug command.

I very much agree with that sentiment. This change implements the transition without any deprecation period as the command is not even documented currently and I do not anticipate anyone actually depending on it.

### :memo: Reviewer Checklist

Review this pull request by ensuring the following items:

- [x] All user-facing changes have changelog entries
- [x] User-facing changes are reflected on [vast.io](https://github.com/tenzir/vast/tree/master/web)

### CODE REVIEW

**Review by patszt — APPROVED** [review]

**Comment by mavam** [comment]
Not strictly required for this PR, but upcoming documentation will go to https://vast.io/docs/use/introspect, right?

**Comment by dominiklohmann** [comment]
> Not strictly required for this PR, but upcoming documentation will go to https://vast.io/docs/use/introspect, right?

That I will leave up to you. Just waiting for the Arrow PR to be merged now so CI gets fixed on this one.

**Comment by tobim** [comment]
I believe this PR was missing a `git mv taxonomy-dump show-taxonomies`?

**Comment by dominiklohmann** [comment]
> I believe this PR was missing a `git mv taxonomy-dump show-taxonomies`?

Already fixed in #2638 directly. We also just noticed. This got auto-merged accidentally while rewriting the branch protections for #2655.

**Pull request merged**
