### PR TITLE
Add missing concepts for Suricata events

### PR DESCRIPTION
**Pull request by tobim**
### :memo: Checklist

- [x] All user-facing changes have changelog entries.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
Is this exempt from the feature freeze? Should we merge this and add an rc2?

**Comment by tobim** [comment]
In my opinion this is very low risk, but I would not want to force an rc2 just for this.

**Comment by dominiklohmann** [comment]
Then let's only merge this if we need another mixup.

**Review by lava — APPROVED** [review]
I did not verify in detail that the updated concept fields are correct, but the gist of the PR looks good to me.

**Pull request merged**
