### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by dominiklohmann**
###  :notebook_with_decorative_cover: Description

This just removes some files that weren't mentioned anywhere anymore.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

🤷‍♂️

### CODE REVIEW

**Comment by mavam** [comment]
Can we keep `libvast/vast/detail/varbyte.hpp`? I need this soon for something again.

**Comment by dominiklohmann** [comment]
It's back in @mavam.

**Comment by mavam** [comment]
Thanks! Sorry to bother you once more. I'd like to keep the zig-zag coding as well. 🙏

**Comment by dominiklohmann** [comment]
> Thanks! Sorry to bother you once more. I'd like to keep the zig-zag coding as well. 🙏

Also back in.

**Review by mavam — APPROVED** [review]

**Pull request merged**
