### PR TITLE
Run commands from scripts

### PR DESCRIPTION
**Pull request by rdettai**
Currently, you can run commands on the VAST lambda or server only from a string passed as option to a CLI commands. This makes it hard to provide more complex commands, among other because of escaping issues. It would be simpler if we could execute commands from a script store in a file.

### :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [vast.io](https://vast.io), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

- docker is now binding the entire file system to make it possible to specify files that are outside the repository tree (@dispanser, this should also fix the git worktree issues) -> see `cloud/vast/vast-cloud`
- `--cmd` option of `run-lambda` and `execute-command` now gets the
- `run-lambda` and `execute-command` also take an `--env` list option to pass environment variables to the provided script. 
- also included an unrelated quick fix in `cloud/aws/terraform/common/s3notif/inputs.tf` because the dns resolution sometimes mysteriously fails with the default s3 domain

### CODE REVIEW

**Review by dispanser — APPROVED** [review]
tested with `run-lambda file:///...`

**Comment by rdettai** [comment]
I will add a few tests before merging

**Comment by rdettai** [comment]
https://github.com/tenzir/vast/actions/runs/2719686571

**Comment by rdettai** [comment]
https://github.com/tenzir/vast/runs/7539753040

**Pull request merged**
