### PR TITLE
Compile with C++20

### PR DESCRIPTION
**Pull request by tobim**
### :notebook_with_decorative_cover: Description

All supported build systems have recent compiler versions, so it's time to pull the trigger.

Issues that I ran into:
- `this` is no longer implicitly captured with `[=]`
- `concept` is now a keyword
- typed actor states should not have typed actor handles of different actors as their first member variable any more

### :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Build and run locally.

### CODE REVIEW

**Comment by tobim** [comment]
I'm leaning towards dropping the support for AppleClang. Devs working on mac can easily install clang via homebrew.

**Comment by dominiklohmann** [comment]
> I'm leaning towards dropping the support for AppleClang. Devs working on mac can easily install clang via homebrew.

Yep, I agree. Just gotta provide instructions for @mavam, which essentially boil down to putting this into your `zshrc`:

```zsh
export PATH="$(brew --prefix llvm)/bin:${PATH}"
export LDFLAGS="-Wl,-rpath,$(brew --prefix llvm) ${LDFLAGS}"
export CPPFLAGS"-isystem $(brew --prefix llvm)/include ${CPPFLAGS}"
export CXXFLAGS"-isystem $(brew --prefix llvm)/include/c++/v1 ${CXXFLAGS}"
```

**Comment by JoeLoser** [comment]
Super excited to see this land and start using concepts and requires expressions!

**Comment by lava** [comment]
Adding my research here since this bullet point

> typed actor states should not have typed actor handles of different actors as their first member variable any more

had me confused a bit. As far as I understand, it's due to the new "parenthesized aggregate initialization": This function in CAF's `stateful_actor.hpp`

```
  template <class T>
  typename std::enable_if<std::is_constructible<State, T>::value>::type
  cr_state(T arg) {
    new (&state_) State(arg);
  }
```
was formerly disabled via SFINAE, but now a line like this (which is probably similar to what is used in the implementation of `is_constructible`)

```
    new (&state_) State(arg);
```

is parsed as a parenthesized aggregate initializer, turning the condition to true and leading us to take the wrong branch.

An alternative to switching the order would probably be to add defaulted constructors, but either way should be fine.

**Comment by mavam** [comment]
@dominiklohmann have you tested these shell settings? I am asking because they contain two syntax errors (missing space). I also wonder whether there's a more local way of enabling C++ on macOS that doesn't mess with global compilation flags.

**Comment by dominiklohmann** [comment]
> @dominiklohmann have you tested these shell settings? I am asking because they contain two syntax errors (missing space).

Yes, I use them locally all the time. Sorry for the typos, I missed two equality signs when translating from my usual typeset-foo to export.

You might also need to set CC and CXX to `clang` and `clang++` respectively.

This is what I generally recommend on macOS for building VAST:

```bash
export PATH="$(brew --prefix llvm)/bin:${PATH}"
export CC="$(brew --prefix llvm)/bin/clang"
export CXX="$(brew --prefix llvm)/bin/clang++"
export LDFLAGS="-Wl,-rpath,$(brew --prefix llvm) ${LDFLAGS}"
export CPPFLAGS="-isystem $(brew --prefix llvm)/include ${CPPFLAGS}"
export CXXFLAGS="-isystem $(brew --prefix llvm)/include/c++/v1 ${CXXFLAGS}"

export CMAKE_GENERATOR='Ninja'
export CMAKE_C_COMPILER_LAUNCHER='ccache'
export CMAKE_CXX_COMPILER_LAUNCHER='ccache'
export DOCKER_BUILDKIT=1
```

> I also wonder whether there's a more local way of enabling C++ on macOS that doesn't mess with global compilation flags.

Nothing's stopping you from setting `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` for VAST only, although you will rarely experience issues with using LLVM clang by default over AppleClang. And if you do, you can always use `xcrun make` over `make` (and similar) to force usage of the default dev toolkit configured via `xcode-select` to get back to AppleClang.

**Comment by lava** [comment]
Not patching CAF works in CI because we add `-Wno-error=deprecated` to the CI flags, but if you build the branch locally in debug mode you get a ton of these warnings for almost every file that interacts with CAF's actor system:

```
[ 60%] Building CXX object libvast/CMakeFiles/libvast.dir/src/system/application.cpp.o
In file included from /home/benno/src/vast/master/libvast/aux/caf/libcaf_core/caf/scoped_actor.hpp:24,
                 from /home/benno/src/vast/master/libvast/vast/detail/logger_formatters.hpp:36,
                 from /home/benno/src/vast/master/libvast/vast/logger.hpp:43,
                 from /home/benno/src/vast/master/libvast/vast/format/json.hpp:21,
                 from /home/benno/src/vast/master/libvast/src/system/application.cpp:19:
/home/benno/src/vast/master/libvast/aux/caf/libcaf_core/caf/blocking_actor.hpp: In lambda function:
/home/benno/src/vast/master/libvast/aux/caf/libcaf_core/caf/blocking_actor.hpp:334:15: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
  334 |     auto cb = [=](receive_cond& rc) mutable {
      |               ^
/home/benno/src/vast/master/libvast/aux/caf/libcaf_core/caf/blocking_actor.hpp:334:15: note: add explicit ‘this’ or ‘*this’ capture
```

**Comment by dominiklohmann** [comment]
> if you build the branch locally in debug mode you get a ton of these warnings for almost every file that interacts with CAF's actor system:

I don't get a single warning using Clang, why would that be different? Did you try with the latest branch and the submodule from the last commit?

**Comment by lava** [comment]
Yes, I used this branch and updated the submodule. Clang doesn't issue a warning for this, so you would not see anything when compiling with clang:

```
benno@bourbaki:~/code/cpp$ cat lambda-this-copy.cpp 
class A {
  void f() {
    int x = [=] {
      return y;
    }();
  }

  int y;
};
benno@bourbaki:~/code/cpp$ clang++ -c lambda-this-copy.cpp -std=c++20
benno@bourbaki:~/code/cpp$ g++ -c lambda-this-copy.cpp -std=c++20
lambda-this-copy.cpp: In lambda function:
lambda-this-copy.cpp:3:13: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
    3 |     int x = [=] {
      |             ^
lambda-this-copy.cpp:3:13: note: add explicit ‘this’ or ‘*this’ capture
```

**Comment by tobim** [comment]
I think the best way to handle this is to treat bundled CAF headers as system headers. This happens automatically for imported targets in CMake, hence the absence of those warnings when linking against a system provided CAF.

This should be possible in CMake by copying the contents of `INTERFACE_INCLUDE_DIRECTORIES` to `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES`. Check [the docs](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_SYSTEM_INCLUDE_DIRECTORIES.html#prop_tgt:INTERFACE_SYSTEM_INCLUDE_DIRECTORIES).

**Comment by dominiklohmann** [comment]
> This should be possible in CMake

It is indeed. @lava please test if this fixes your issues.

**Review by lava — APPROVED** [review]
Things seem to work nicely now. From my testing, cmake is also smart enough to filter out `/usr/include` from the generated `-isystem` directives, avoiding the error described in https://stackoverflow.com/questions/37218953/isystem-on-a-system-include-directory-causes-errors

**Review by dominiklohmann — APPROVED** [review]
Let's ship it!

**Pull request merged**
