### PR TITLE
Add example compaction configuration

### PR DESCRIPTION
**Pull request by satta**
This PR adds an example configuration for the compaction plugin, affecting Suricata data.

### :memo: Checklist

- [n/a] All user-facing changes have changelog entries.
- [n/a] The changes are reflected on [vast.io](https://vast.io), if necessary.
- [X] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Please ensure that the appropriate versions of the keywords in transition (`pipeline`/`transform` etc.) are used.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
I'm fine with this PR generally, but I think the file deserves some explanatory comments and the `compaction` directory a README. We also already bundle an example configuration with the `compaction` plugin, so maybe it'd be better to move the content over there rather than to duplicate it here.

**Comment by mavam** [comment]
> so maybe it'd be better to move the content over there rather than to duplicate it here.

I think it would be nice to link this from the docs, or even slurp it in on one page entirely. From this perspective, having it here makes more sense to me.

**Comment by satta** [comment]
Well, maybe I got it wrong but the idea was to have a place to keep the config we discussed and work on it together. I was unsure whether a PR to the main VAST repo would even be the right thing to do, since this is far from ready.

The compaction plugin isn't open source, is it? So it's difficult to open a PR against that ;)

**Comment by mavam** [comment]
> Well, maybe I got it wrong but the idea was to have a place to keep the config we discussed and work on it together. I was unsure whether a PR to the main VAST repo would even be the right thing to do, since this is far from ready.

I think that's acceptable. Part of putting our documentation out there in a soon-to-be-reached state helped us a lot to see whether the concepts hold up in a bigger picture. This would be a similar approach.

> The compaction plugin isn't open source, is it? So it's difficult to open a PR against that ;)

In general, the idea is to put everything in the open-source documentation, but mark the places explicitly when they required closed-source plugins. We do that already for the matcher, so this would be the same pattern here.

@dominiklohmann and I will take the discussion on how to improve this workflow elsewhere. If you have an idea, don't hold back with feedback. 🙂

**Comment by dominiklohmann** [comment]
@satta I'm in the process of rolling this out for testing on our internal testbed as part of the v2.2 release process.

**Comment by satta** [comment]
I think you might need to remove the `summarize` from the plugin list since that's included now

**Comment by dominiklohmann** [comment]
I had to rewrite much more actually, this is the configuration we're testing now:

```yaml
vast:
  plugins:
    - bundled

  db-directory: "/var/lib/vast/db"

  log-file: "/var/log/vast/server.log"
  log-rotation-threshold: 256MiB

  store-backend: segment-store
  start:
    disk-budget-high: 95
    disk-budget-low: 90
    disk-budget-check-binary: /opt/vast/dbsize.sh
  
  max-queries: 10
  # max-taste-partitions: 10
 
  console-format: "[%l] %v"
  console-sink: stderr

  enable-metrics: true
  metrics:
    self-sink:
      enable: false
      slice-size: 128
    file-sink:
      enable: true
      real-time: true
      path: "/tmp/vast-metrics.log"
    uds-sink:
      enable: true
      real-time: true
      path: "/tmp/vast-metrics.sock"
      type: "datagram"

  pipelines:
    aggregate-flows:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            flow.pkts_toserver: sum
            flow.pkts_toclient: sum
            flow.bytes_toserver: sum
            flow.bytes_toclient: sum
            flow.start: min
            flow.end: max
            flow.alerted: any
            src_port: distinct
            community_id: distinct
      - extend:
          fields:
            event_type: flow_agg
      - rename:
          schemas:
            - from: suricata.flow
              to: suricata.flow_agg

    aggregate-dns:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - dns.rrname
            - dns.rrtype
            - dns.type
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            src_port: distinct
            community_id: distinct
            dns.rcode: distinct
            dns.answers: distinct
      - extend:
          fields:
            event_type: dns_agg
      - rename:
          schemas:
            - from: suricata.dns
              to: suricata.dns_agg

    aggregate-snmp:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - snmp
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            community_id: distinct
      - extend:
          fields:
            event_type: snmp_agg
      - rename:
          schemas:
            - from: suricata.snmp
              to: suricata.snmp_agg

    aggregate-smb:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - smb.session_id
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            smb.id: max
            smb.size: sum
            smb.command: distinct
            smb.filename: distinct
            smb.disposition: distinct
            smb.share: distinct
            smb.ntlmssp.host: distinct
            smb.ntlmssp.domain: distinct
            smb.ntlmssp.user: distinct
            smb.named_pipe: distinct
            smb.share_type: distinct
      - extend:
          fields:
            event_type: smb_agg
      - rename:
          schemas:
            - from: suricata.smb
              to: suricata.smb_agg

    aggregate-http:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - http.hostname
            - http.url
            - http.http_port
            - http.http_method
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            http.length: sum
            http.user_agent: distinct
            http.content_type: distinct
            http.referer: distinct
            http.status: distinct
      - extend:
          fields:
            event_type: http_agg
      - rename:
          schemas:
            - from: suricata.http
              to: suricata.http_agg

    aggregate-tls:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - tls.sni
            - tls.fingerprint
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            smb.size: sum
            tls.ja3.hash: distinct
            tls.ja3s.hash: distinct
            tls.subject: sample
            tls.issuerdn: sample
            tls.serial: sample
            tls.notbefore: sample
            tls.notafter: sample
      - extend:
          fields:
            event_type: tls_agg
      - rename:
          schemas:
            - from: suricata.tls
              to: suricata.tls_agg

plugins:
  compaction:
    time:
      interval: 1 hour
      step-size: 1
      rules:
        - after: 1 day
          name: flow-reduction
          pipeline: aggregate-flows
          types:
            - suricata.flow
        - after: 1 day
          name: dns-reduction
          pipeline: aggregate-dns
          types:
            - suricata.dns
        - after: 1 day
          name: snmp-reduction
          pipeline: aggregate-snmp
          types:
            - suricata.snmp
        - after: 1 day
          name: smb-reduction
          pipeline: aggregate-smb
          types:
            - suricata.smb
        - after: 4 days
          name: http-reduction
          pipeline: aggregate-http
          types:
            - suricata.http
        - after: 4 days
          name: tls-reduction
          pipeline: aggregate-tls
          types:
            - suricata.tls

    space:
      interval: 30 min
      step-size: 1
      mode: weighted-age
      disk-budget-high: 80 
      disk-budget-low: 70
      scan-binary: /opt/vast/dbsize.sh
```

**Comment by satta** [comment]
Many thanks, I was just starting to do that after trying out the new 2.2 build. Will test the above as well 👍🏻

**Comment by dominiklohmann** [comment]
Note that I divided all the timings by 7 to make this easier to test, and I reduced the step sizes to 1 because the server I've rolled this out on is a bit memory-constrained.

**Comment by dominiklohmann** [comment]
@satta this is the configuration that we ended up using on our testbed, and it works really nicely. Can you replace the contents of the vast.yaml in the PR with it?

```yaml
vast:
  pipelines:
    aggregate-flows:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            flow.pkts_toserver: sum
            flow.pkts_toclient: sum
            flow.bytes_toserver: sum
            flow.bytes_toclient: sum
            flow.start: min
            flow.end: max
            flow.alerted: any
            src_port: distinct
            community_id: distinct
            count:
              count: event_type
      - extend:
          fields:
            event_type: flow_agg
      - rename:
          schemas:
            - from: suricata.flow
              to: suricata.flow_agg

    aggregate-dns:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - dns.rrname
            - dns.rrtype
            - dns.type
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            src_port: distinct
            community_id: distinct
            dns.rcode: distinct
            dns.answers: distinct
            count:
              count: event_type
      - extend:
          fields:
            event_type: dns_agg
      - rename:
          schemas:
            - from: suricata.dns
              to: suricata.dns_agg

    aggregate-snmp:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - snmp
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            community_id: distinct
            count:
              count: event_type
      - extend:
          fields:
            event_type: snmp_agg
      - rename:
          schemas:
            - from: suricata.snmp
              to: suricata.snmp_agg

    aggregate-smb:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - smb.session_id
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            smb.id: max
            smb.size: sum
            smb.command: distinct
            smb.filename: distinct
            smb.disposition: distinct
            smb.share: distinct
            smb.ntlmssp.host: distinct
            smb.ntlmssp.domain: distinct
            smb.ntlmssp.user: distinct
            smb.named_pipe: distinct
            smb.share_type: distinct
            count:
              count: event_type
      - extend:
          fields:
            event_type: smb_agg
      - rename:
          schemas:
            - from: suricata.smb
              to: suricata.smb_agg

    aggregate-http:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - http.hostname
            - http.url
            - http.http_port
            - http.http_method
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            http.length: sum
            http.user_agent: distinct
            http.content_type: distinct
            http.referer: distinct
            http.status: distinct
            count:
              count: event_type
      - extend:
          fields:
            event_type: http_agg
      - rename:
          schemas:
            - from: suricata.http
              to: suricata.http_agg

    aggregate-tls:
      - summarize:
          group-by:
            - timestamp
            - src_ip
            - dest_ip
            - dest_port
            - proto
            - tls.sni
            - tls.fingerprint
          time-resolution: 1 hour
          aggregate:
            timestamp_min:
              min: timestamp
            timestamp_max:
              max: timestamp
            smb.size: sum
            tls.ja3.hash: distinct
            tls.ja3s.hash: distinct
            tls.subject: sample
            tls.issuerdn: sample
            tls.serial: sample
            tls.notbefore: sample
            tls.notafter: sample
            count:
              count: event_type
      - extend:
          fields:
            event_type: tls_agg
      - rename:
          schemas:
            - from: suricata.tls
              to: suricata.tls_agg

plugins:
  compaction:
    time:
      interval: 1 day
      step-size: 3
      rules:
        - after: 1 day
          name: flow-reduction
          pipeline: aggregate-flows
          types:
            - suricata.flow
        - after: 1 day
          name: dns-reduction
          pipeline: aggregate-dns
          types:
            - suricata.dns
        - after: 1 day
          name: snmp-reduction
          pipeline: aggregate-snmp
          types:
            - suricata.snmp
        - after: 1 day
          name: smb-reduction
          pipeline: aggregate-smb
          types:
            - suricata.smb
        - after: 7 days
          name: http-reduction
          pipeline: aggregate-http
          types:
            - suricata.http
        - after: 7 days
          name: tls-reduction
          pipeline: aggregate-tls
          types:
            - suricata.tls
    space:
      interval: 1 hour
      step-size: 3
      mode: weighted-age
      disk-budget-high: 70
      disk-budget-low: 60
      scan-binary: /opt/vast/dbsize.sh
      weights:
        # Keep aggregated flow, fns, snmp and smb logs 5x longer
        - weight: 5
          types:
            - suricata.flow_agg
            - suricata.dns_agg
            - suricata.snmp_agg
            - suricata.smb_agg
        # Keep aggregated http and tls logs 10x longer
        - weight: 10
          types:
            - suricata.http_agg
            - suricata.tls_agg
```

**Comment by satta** [comment]
Done. Thanks!

**Comment by mavam** [comment]
@dominiklohmann is anything holding this PR up from being merged? IIRC it works.

We could consider linking it from the docs. In this case it would be nice to somehow guarantee that the config is always valid syntax through CI.

**Comment by dominiklohmann** [comment]
> @dominiklohmann is anything holding this PR up from being merged? IIRC it works.
> We could consider linking it from the docs. In this case it would be nice to somehow guarantee that the config is always valid syntax through CI.

Yes. It's lacking documentation, we don't install it yet as an example config file (unlike the vast.yaml.example file in the repository root) and it's in the wrong place, because it documents a closed-source plugin in the open-source repository, which makes it so we cannot test whether the file is correct.

I was considering two options for this:
1. We move the file over to the compaction plugin and install it with an example. We also add comments inline and test it in a unit or integration test.
2. We inline the example into the compaction configuration as an end-to-end example.

I am currently favoring (2) as that's much less effort, and having end-to-end examples in the docs is nice anyways.

**Comment by mavam** [comment]
> We inline the example into the compaction configuration

That would be in the docs then?

**Comment by dominiklohmann** [comment]
> > We inline the example into the compaction configuration
> 
> That would be in the (open) docs then?

Yes, I would say so.

**Comment by dominiklohmann** [comment]
@satta I just discussed this at length with @mavam and @lava and this is the plan we came up with:

I'll take the example configuration we had here, and move it over to the compaction plugin, which will bundle it with every installation. We will also add tests to our CI to ensure that the configuration is valid and produces the expected output.

In addition, we want to take a subset of this and use it instead of the [current configuration example](https://vast.io/docs/use-vast/transform#trigger-a-compaction-manually) for compaction in our docs.

I scheduled this for myself for in ~2-3 weeks. I have a few other higher priority things on my plate until then, but we don't want this PR to stay open all that long anymore.

**Comment by satta** [comment]
Cool, agreed. Do we want to close this here then?

**Pull request closed without merging**
