### PR TITLE
Remove /etc as hardcoded sysconfdir from Nix build 

### PR DESCRIPTION
**Pull request by dominiklohmann**
### :notebook_with_decorative_cover: Description

This PR contains two changes:

- Our static binaries behaved differently than our regular relocatable installations: They were looking for the global configuration in `/etc/vast/vast.yaml` rather than the expected `<prefix>/etc/vast/vast.yaml`. This change makes them behave just like regular relocatable installations.
   For users, this means that configuration files at `/etc/vast/vast.yaml` need to be moved accordingly.
- We now install an example config file alongside VAST.

### :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Read the code, try the static binary from CI.

### CODE REVIEW

**Comment by mavam** [comment]
Why is the example config all commented out?

**Comment by dominiklohmann** [comment]
> Why is the example config all commented out?

That's intentional: It's an example config file, and if we install it, then we don't want it to mesh with the actual defaults. Unless we find a way to guarantee that defaults and example config are in sync (which we don't right now), I'd rather have everything commented out.

**Comment by mavam** [comment]
I would agree if it's an actual `.yaml` file. But it's an `.example` file that VAST doesn't look at anyway on startup.

The UX of reading a properly syntax-highlighted file and separate the tuning knobs from the content is not to be dismissed, I think.

**Comment by dominiklohmann** [comment]
> I would agree if it's an actual `.yaml` file. But it's an `.example` file that VAST doesn't look at anyway on startup.

Take a look at the changed CMake code in this PR: We install this file to `<prefix>/etc/vast/vast.yaml`.

**Comment by mavam** [comment]
I wonder whether we should simply keep the uncommented example file in the repo and install a transformation (e.g., through `sed`) at the destination. That would make at least maintaining the example config file easier and avoid mistakes.

**Review by mavam — APPROVED** [review]
If you can get `awk` installed in Nix, we're in business in CI.

**Pull request merged**
