### PR TITLE
Introduce a stress test

### PR DESCRIPTION
**Pull request by tobim**
###  :notebook_with_decorative_cover: Description

A little bash script to test robustness against many simultaneous imports and exports.

###  :memo: Checklist

- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

By commit.
It should be possible to run `cmake --build <dir> --target stress`.
Note that <Ctrl-c> while the script is running won't cleanup properly. No, sigkill to the process group doesn't help. Ideas welcome.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
I'm taking this branch over temporarily, and rebased onto recent master.

**Comment by dominiklohmann** [comment]
This whole `2021-02-22T14:40:12.8697689Z ##[error]Process completed with exit code 137.` business within the Docker container smells like an out-of-memory error to me.

**Comment by tobim** [comment]
Closing this for lack of progress. We should take the time to propose a solution that doesn't rely on bash.

**Comment by tobim** [comment]
I just remembered, this also aligns the directory structure of `integration/data` with the import formats. I would still like to do this part. Will open a dedicated PR as soon as I have time.

**Pull request closed without merging**
