### PR TITLE
Introduce regression tests

### PR DESCRIPTION
**Pull request by dominiklohmann**
This adds automatic regression tests to our CI, comparing the current build against all previously tagged releases.

### CODE REVIEW

**Comment by rdettai** [comment]
@dominiklohmann 
- Can I remove the modifications to the compose files?
- Can you review this (cannot set you as reviewer as this is your PR originally 😄 )

**Comment by dominiklohmann** [comment]
Yes and yes @rdettai. Will take a look later today, just lmk when it's ready.

**Review by dominiklohmann — COMMENTED** [review]
I cannot approve my own PR, but this is a fantastic piece of work. Would you mind squashing it to remove all my old bogus commit messages, and then approving + merging it yourself, @rdettai?

**Review by rdettai — APPROVED** [review]

**Comment by rdettai** [comment]
good to know that if you hijack someones PR you can override all his commits and then auto approve yourself 😄

**Comment by dominiklohmann** [comment]
> good to know that if you hijack someones PR you can override all his commits and then auto approve yourself 😄

We can disable that in branch protections, prohibiting a merge if the approval is from the last person committing to a branch.

**Pull request merged**
