### PR TITLE
Disable SIMD for nix-based CI builds

### PR DESCRIPTION
**Pull request by tobim**
###  :notebook_with_decorative_cover: Description

This turns off simd in Apache Arrow for the CI build type.

### CODE REVIEW

**Comment by mavam** [comment]
Can you elaborate why we should do this?

**Comment by dominiklohmann** [comment]
How does this even work? Don't you need to depend on a custom build of Arrow that builds with `ARROW_SIMD_LEVEL=NONE`?

**Comment by tobim** [comment]
> Can you elaborate why we should do this?

We need an x86_64 binary that doesn't use any simd instructions beyond SSE2. Arrow's default is SSE4.2, so a vast linked to that won't work on old hardware.

**Comment by tobim** [comment]
> How does this even work? Don't you need to depend on a custom build of Arrow that builds with `ARROW_SIMD_LEVEL=NONE`?

Nix is a declarative system, if the requested library doesn't exist it gets built on-demand.

**Comment by dominiklohmann** [comment]
> Nix is a declarative system, if the requested library doesn't exist it gets built on-demand.

Thanks for the explanation. Will take a look at this once the CI runs through.

**Comment by tobim** [comment]
[ch20593]

**Review by dominiklohmann — APPROVED** [review]
LGTM!

**Pull request merged**
