### PR TITLE
Remove unnecessary job dependencies in CI

### PR DESCRIPTION
**Pull request by dominiklohmann**

### CODE REVIEW

**Review by mavam — APPROVED** [review]

**Comment by mavam** [comment]
It looks like the website CI run only ran now and revealed that my previous PR contained broken links. 😒

**Comment by dominiklohmann** [comment]
Afaict that's a timing issue with a command not properly blocking for long enough. This we can only fix by reworking how we do blocking imports. I'd just re-run for now.

**Comment by mavam** [comment]
Okay, I fixed the broken link (needed a force-push after rebasing). Let's see where this gets us.

**Comment by dominiklohmann** [comment]
Yes, that's a bug in TheHive starting up. It's why the job is not required for branch protections to pass.

**Pull request merged**
