### PR TITLE
Revamp Cloud commands

### PR DESCRIPTION
**Pull request by rdettai**
Some of the commands where named at the creation of the VAST Cloud tooling, and the scope has changed quite a bit since then.  This PR operates some long needed command renaming to provide a more streamlined UX. This is okay because there is a disclaimer in the documentation indicating that these APIs are subject to change.

### :memo: Reviewer Checklist

Review this pull request by ensuring the following items:

- [ ] All user-facing changes have changelog entries
- [x] User-facing changes are reflected on [vast.io](https://github.com/tenzir/vast/tree/master/web)

### CODE REVIEW

**Comment by rdettai** [comment]
[Terraform](https://github.com/tenzir/vast/actions/workflows/terraform.yaml?query=branch%3Atopic%2Frevamp-cloud-cmds)

**Comment by dispanser** [comment]
> [Terraform](https://github.com/tenzir/vast/actions/workflows/terraform.yaml?query=branch%3Atopic%2Frevamp-cloud-cmds)

should I worry about this?

**Comment by rdettai** [comment]
A little bit but not too much 😄 I think it comes from:
- me forgetting to hit save on a file
- a problem on the base image

I pinned the version to the latest release and commited the missing file, it should go 🟢 now

**Review by dispanser — APPROVED** [review]
This renaming brings some appreciated consistency :+1: 

Approving modulo CI run, not tested locally due to time constraints.

**Pull request merged**
