### PR TITLE
Upgrade web dependencies

### PR DESCRIPTION
**Pull request by mavam**
Maintenance PR to upgrade dependencies. If CI checks out, give it a go.

### CODE REVIEW

**Review by dispanser — APPROVED** [review]
You may have to rebase to current master to please the CI (brew install problem)

**Comment by dominiklohmann** [comment]
I took the liberty to rebase this after fixing the CI on master.

**Comment by mavam** [comment]
Looks like we need to wait for #2601.

**Comment by dominiklohmann** [comment]
> Looks like we need to wait for #2601.

You can already merge this, the macOS CI job is temporarily not a required job.

**Pull request merged**
