### PR TITLE
Add editorconfig file

### PR DESCRIPTION
**Pull request by tobim**

### CODE REVIEW

**Comment by mavam** [comment]
I'm not sure if this is working, but is it possible to move this file to our new `.github` repo so that it's available to all repos at our org?

**Comment by dominiklohmann** [comment]
> I'm not sure if this is working, but is it possible to move this file to our new `.github` repo so that it's available to all repos at our org?

That's for Community Health files only (except license and readme).

**Comment by mavam** [comment]
Okay, I just wonder how we'll keep this one in sync with other repos.

**Comment by tobim** [comment]
> Okay, I just wonder how we'll keep this one in sync with other repos.

This file saves a similar purpose as `.clang-format`. It should not be necessary to clone another repo to set a few editor defaults. Maybe we can introduce a canonical copy in a central scaffold repository from which the others are synced, but that feels very over engineered to me.

**Comment by tobim** [comment]
> Lgtm. We don't have any Makefiles anymore, right?

I removed that section before opening the PR, you must have had an older version in the cache.

**Pull request merged**
