### PR TITLE
Use SPDX license and copyright identifiers

### PR DESCRIPTION
**Pull request by dominiklohmann**
###  :notebook_with_decorative_cover: Description

This was mostly done in an automated fashion:

```bash
banner='\/\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\n \*                    _   _____   __________                                  \*\n \*                   | | \/ \/ _ | \/ __\/_  __\/     Visibility                   \*\n \*                   | |\/ \/ __ |_\\ \\  \/ \/          Across                     \*\n \*                   |___\/_\/ |_\/___\/ \/_\/       Space and Time                 \*\n \*                                                                            \*\n \* This file is part of VAST\. It is subject to the license terms in the       \*\n \* LICENSE file found in the top-level directory of this distribution and at  \*\n \* http:\/\/vast\.io\/license\. No part of VAST, including this file, may be       \*\n \* copied, modified, propagated, or distributed except according to the terms \*\n \* contained in the LICENSE file\.                                             \*\n \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\/' && for file in $(git ls-files); do gsed -i -z "s/$banner/\/\/ This file is part of VAST. It is subject to the license terms in the LICENSE\n\/\/ file found in the top-level directory of this distribution.\n\/\/ SPDX-FileCopyrightText: © $(git log --format="format:%ci" --reverse -- $file | head -1 | cut -d- -f1) Tenzir GmbH <engineering@tenzir.com>\n\/\/ SPDX-License-Identifier: BSD-3-Clause/" $file; done
```

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

🤷‍♂️

### CODE REVIEW

**Comment by tobim** [comment]
Why did you add the first 2 lines?

**Comment by dominiklohmann** [comment]
> Why did you add the first 2 lines?

See link in the associated story. They aren't necessary, but they refuse some possible confusion by mentioning the LICENSE file explicitly. Personally I don't care whether they're there or not—I just wanted to put this out here so we actually get going on this instead of having this rather small story going on forever.

**Comment by tobim** [comment]
Can you re-run the script without the 2 first lines? I think we have a window to get this through now.

**Comment by dominiklohmann** [comment]
> Can you re-run the script without the 2 first lines? I think we have a window to get this through now.

Done. Please check back.

**Comment by tobim** [comment]
somehow `fwd.hpp` and `partition.hpp` as indented? Can you run `git format`?

**Comment by dominiklohmann** [comment]
> somehow `fwd.hpp` and `partition.hpp` are indented? Can you run `git format`?

👀 fixed

**Review by tobim — APPROVED** [review]
Not a functional change, so nothing that can be tested.

**Pull request merged**
