### PR TITLE
Upgrade to Arrow 2.0

### PR DESCRIPTION
**Pull request by dominiklohmann**
###  :notebook_with_decorative_cover: Description

In order to avoid pinning Arrow 1.0.1 indefinitely, we must upgrade our code base to be compatible with Arrow 2.0.

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/vast](https://docs.tenzir.com/vast), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

### :dart: Review Instructions

Commit-by-commit. All the changes should be covered by CI.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
This PR is blocked by an upstream CMake change that we can either try to work around or wait to be resolved. I've added the `blocked` label accordingly.

**Comment by dominiklohmann** [comment]
I rebased this onto #1140 because that PR also fixed the deprecation warnings. The CI, however, is still failing for likely external reasons.

**Comment by tobim** [comment]
See for the upstream issue, this will only be fixed with the release of Arrow 3.0.0. Maybe we can add a workaround for `RE2` in the meantime.

**Comment by dominiklohmann** [comment]
I'm not sure whether we want to add a workaround. VAST itself works fine. Maybe we just close this PR and refer to the upstream issue if need be.

**Comment by dominiklohmann** [comment]
I'm closing this PR after today's discussion of the issue.

@tobim if you want to implement the workaround, feel free to open a new PR that fixes the issue in the meantime. Otherwise we'll just continue pinning Arrow to 1.0 for our Ubuntu CI and Dockerfiles.

**Pull request closed without merging**
