### PR TITLE
Warn when skipping JSONL because no type matches

### PR DESCRIPTION
**Pull request by dominiklohmann**

### CODE REVIEW

**Comment by tobim** [comment]
Could we add some way of log flooding prevention? If there is a general mismatch it will print this message on every line...

**Comment by dominiklohmann** [comment]
We could print only when sending out the status report, but then we'd lose information about the line itself. I'm not sure which is preferable.

**Comment by tobim** [comment]
We can still keep a copy of the line and have a counter for how often this branch is taken. The log message from the status could read:
```
VAST_WARNING(this, "failed to find a matching type at line",
                   lines_->line_number(), ":", failed_first, "and", failed_count, "others");
```

**Comment by dominiklohmann** [comment]
I have opted for the middle ground of printing the first line exactly and then printing a summary when the status is requested.

```
2020-06-04T12:43:56.925 vast.format.json.reader failed to find a matching type at line 1 : {"UtcTime":"2020-05-18 09:49:07.594","DestinationPortName":"ms-wbt-server","SourcePortName":"-","SourceIp":"51.91.69.20","RuleName":"RDP","SourceIsIpv6":"false","SourceHostname":"ns61208963.ip-51-91-69.eu","DestinationHostname":"EC2AMAZ-ESHNN19.eu-central-1.compute.internal","DestinationIsIpv6":"false","DestinationIp":"172.31.5.93","Image":"C:\\Windows\\System32\\svchost.exe","DestinationPort":"3389","ProcessId":"68","Protocol":"tcp","SourcePort":"56637","User":"NT AUTHORITY\\NETWORK SERVICE","Initiated":"false","ProcessGuid":"{7899F400-C773-5EB3-0E00-000000004A01}"}
2020-06-04T12:43:56.965 vast.format.json.reader failed to find a matching type for 2500 of 2500 recent lines
```

**Comment by 0ortmann** [comment]
Depending on the loglevel setting I'd argue that flooding the log is nothing bad. (e.g., `verbose`)

**Pull request merged**
