### PR TITLE
Upgrade docusaurus to ^2.3.1 and update all yarn packages

### PR DESCRIPTION
**Pull request by dit7ya**
All yarn packages were upgraded via the following commands

```
yarn upgrade
syncyarnlock
yarn install
```

No version have been upgraded with breaking changes (major semver is preserved).

https://github.com/vasilevich/sync-yarnlock-into-packagejson

### CODE REVIEW

**Review by mavam — APPROVED** [review]
LGTM.

@dominiklohmann may have an idea how to fix the regression test failures in CI.

**Comment by dominiklohmann** [comment]
> @dominiklohmann may have an idea how to fix the regression test failures in CI.

I'll forward that question to @rdettai, the failure makes little sense to me.

**Comment by rdettai** [comment]
when running 
```
docker run --pull=always --rm --name vast-regression -e VAST_CONSOLE_VERBOSITY=verbose -v vast-regression:/var/lib/vast/ ghcr.io/tenzir/vast:topic-docusaurus-upgrade start
```

I get
```
vast: error while loading shared libraries: libarrow.so.1100: cannot open shared object file: No such file or directory
```

It seems that the docker image build itself is broken, and as they are no tests in the `docker-vast`  job itself and the `docker-compose` job is skipped, it bubbles up only here.

**Comment by dominiklohmann** [comment]
Ah, I figured it out. @dit7ya do you mind if I push the fix directly onto this?

**Pull request merged**
